# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='salary',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
