# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0002_auto_20170926_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='salary',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
