# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0003_auto_20170926_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='height_feet',
            new_name='height_inch_max',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='height_inch',
            new_name='height_inch_min',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='weight',
            new_name='weight_min',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='age',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='salary',
        ),
        migrations.AddField(
            model_name='preference',
            name='age_max',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='preference',
            name='age_min',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='preference',
            name='height_feet_max',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='preference',
            name='height_feet_min',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='preference',
            name='salary_range',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='preference',
            name='weight_max',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_range',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_feet',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
