# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0004_auto_20170926_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='weight_max',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='weight_min',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AddField(
            model_name='preference',
            name='body_type',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='body_type',
            field=models.IntegerField(default=2),
        ),
    ]
