# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0005_auto_20170926_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='preference',
            name='age_deal_breaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='body_deal_breaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='height_deal_breaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='salary_deal_breaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=6),
        ),
    ]
